services:
  app:
    build: .
    container_name: vagos-software-api
    env_file: ".env"
    ports:
      - "5000:5000"
    volumes:
      - ./src:/usr/src/app/src
      - ./resources:/usr/src/app/resources
      - ./package.json:/usr/src/app/package.json
    command: sh -c "npm install && npx ts-node-dev src/index.ts"
    depends_on:
      - db

  db:
    image: postgres:12.19-bookworm
    container_name: vagos-software-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db-data:
