
insert into blogs 
values 	(1,1,1,'Ramblings about a runner videogame similar to super hexagon', '

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer congue velit vitae tortor mattis, eget aliquam felis fermentum. Nunc magna orci, posuere quis convallis ut, ornare ac ligula. Curabitur ultrices rutrum nulla nec accumsan. Aliquam sit amet lacus semper, laoreet odio sit amet, volutpat odio. Mauris sagittis, eros non gravida commodo, libero nibh faucibus erat, at tincidunt ipsum lorem a dui. Nam neque nisl, faucibus sed sapien quis, efficitur sodales augue. Donec volutpat elit ac odio gravida porta.

Vivamus vulputate faucibus erat, ac viverra metus pretium et. Nulla lorem est, lobortis sed viverra sed, pulvinar et diam. Praesent eget neque a tortor tempus fringilla. Fusce rutrum magna a neque consequat sagittis. Nulla facilisi. Vivamus scelerisque justo at luctus maximus. Ut congue porttitor libero a vulputate. Morbi at dictum sapien. Nullam auctor ipsum sed volutpat iaculis. Vivamus sed enim quis velit ullamcorper tempor sit amet eu tellus. Vestibulum placerat a augue id accumsan. Curabitur at enim eu erat mattis porta. Pellentesque pharetra sed nunc eu egestas. Nam ut tellus consequat, feugiat ante sed, maximus arcu. Donec eget ipsum nibh.

Proin pellentesque urna ut leo malesuada, sed pharetra urna luctus. Curabitur tincidunt lorem id facilisis condimentum. Fusce vitae est accumsan, vehicula ante et, maximus lacus. Fusce sodales luctus hendrerit. Etiam et facilisis neque. Praesent fringilla, eros vitae fermentum feugiat, turpis nulla mattis neque, ac vulputate velit elit ac tellus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Mauris in neque porttitor, vestibulum tellus sit amet, consectetur velit. Integer at purus congue, molestie nisi vel, cursus purus. Donec tempus congue magna a condimentum. Maecenas a tristique mauris. Pellentesque dolor dolor, iaculis sed venenatis eu, volutpat eget nisl.

Ut vitae dolor egestas, scelerisque enim eu, maximus erat. Praesent in facilisis nisl. Cras pellentesque eros quis felis consectetur pharetra. Mauris mattis augue turpis, ut molestie leo tempor sit amet. Curabitur pretium metus mattis purus laoreet lacinia. Phasellus egestas commodo orci in sollicitudin. Nulla sagittis nulla ligula, et ornare felis hendrerit sit amet.

Donec metus tortor, viverra at erat porttitor, venenatis pulvinar ipsum. Mauris vestibulum orci sit amet felis tristique, sit amet varius nibh venenatis. Nulla ultricies erat non molestie finibus. Duis volutpat ut risus a sollicitudin. Praesent a neque neque. Suspendisse potenti. Maecenas maximus vel nulla non eleifend. Integer vel turpis ante. Praesent lobortis leo vel sapien porttitor, at fringilla nunc faucibus. Maecenas ut leo id quam tempus bibendum eu at ligula. Duis eu nunc non ipsum efficitur cursus et nec sapien. Nullam tempus in purus quis pharetra. ', TRUE, '02-02-2021', now()),
		(2,1,1,'Update on that runner game we were developing', '

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer congue velit vitae tortor mattis, eget aliquam felis fermentum. Nunc magna orci, posuere quis convallis ut, ornare ac ligula. Curabitur ultrices rutrum nulla nec accumsan. Aliquam sit amet lacus semper, laoreet odio sit amet, volutpat odio. Mauris sagittis, eros non gravida commodo, libero nibh faucibus erat, at tincidunt ipsum lorem a dui. Nam neque nisl, faucibus sed sapien quis, efficitur sodales augue. Donec volutpat elit ac odio gravida porta.

Vivamus vulputate faucibus erat, ac viverra metus pretium et. Nulla lorem est, lobortis sed viverra sed, pulvinar et diam. Praesent eget neque a tortor tempus fringilla. Fusce rutrum magna a neque consequat sagittis. Nulla facilisi. Vivamus scelerisque justo at luctus maximus. Ut congue porttitor libero a vulputate. Morbi at dictum sapien. Nullam auctor ipsum sed volutpat iaculis. Vivamus sed enim quis velit ullamcorper tempor sit amet eu tellus. Vestibulum placerat a augue id accumsan. Curabitur at enim eu erat mattis porta. Pellentesque pharetra sed nunc eu egestas. Nam ut tellus consequat, feugiat ante sed, maximus arcu. Donec eget ipsum nibh.

Proin pellentesque urna ut leo malesuada, sed pharetra urna luctus. Curabitur tincidunt lorem id facilisis condimentum. Fusce vitae est accumsan, vehicula ante et, maximus lacus. Fusce sodales luctus hendrerit. Etiam et facilisis neque. Praesent fringilla, eros vitae fermentum feugiat, turpis nulla mattis neque, ac vulputate velit elit ac tellus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Mauris in neque porttitor, vestibulum tellus sit amet, consectetur velit. Integer at purus congue, molestie nisi vel, cursus purus. Donec tempus congue magna a condimentum. Maecenas a tristique mauris. Pellentesque dolor dolor, iaculis sed venenatis eu, volutpat eget nisl.

Ut vitae dolor egestas, scelerisque enim eu, maximus erat. Praesent in facilisis nisl. Cras pellentesque eros quis felis consectetur pharetra. Mauris mattis augue turpis, ut molestie leo tempor sit amet. Curabitur pretium metus mattis purus laoreet lacinia. Phasellus egestas commodo orci in sollicitudin. Nulla sagittis nulla ligula, et ornare felis hendrerit sit amet.

Donec metus tortor, viverra at erat porttitor, venenatis pulvinar ipsum. Mauris vestibulum orci sit amet felis tristique, sit amet varius nibh venenatis. Nulla ultricies erat non molestie finibus. Duis volutpat ut risus a sollicitudin. Praesent a neque neque. Suspendisse potenti. Maecenas maximus vel nulla non eleifend. Integer vel turpis ante. Praesent lobortis leo vel sapien porttitor, at fringilla nunc faucibus. Maecenas ut leo id quam tempus bibendum eu at ligula. Duis eu nunc non ipsum efficitur cursus et nec sapien. Nullam tempus in purus quis pharetra. ', TRUE, '03-03-2021', now()),
		(3,1,1,'Hyper Triangle - 1.0.0 Launch', '

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer congue velit vitae tortor mattis, eget aliquam felis fermentum. Nunc magna orci, posuere quis convallis ut, ornare ac ligula. Curabitur ultrices rutrum nulla nec accumsan. Aliquam sit amet lacus semper, laoreet odio sit amet, volutpat odio. Mauris sagittis, eros non gravida commodo, libero nibh faucibus erat, at tincidunt ipsum lorem a dui. Nam neque nisl, faucibus sed sapien quis, efficitur sodales augue. Donec volutpat elit ac odio gravida porta.

Vivamus vulputate faucibus erat, ac viverra metus pretium et. Nulla lorem est, lobortis sed viverra sed, pulvinar et diam. Praesent eget neque a tortor tempus fringilla. Fusce rutrum magna a neque consequat sagittis. Nulla facilisi. Vivamus scelerisque justo at luctus maximus. Ut congue porttitor libero a vulputate. Morbi at dictum sapien. Nullam auctor ipsum sed volutpat iaculis. Vivamus sed enim quis velit ullamcorper tempor sit amet eu tellus. Vestibulum placerat a augue id accumsan. Curabitur at enim eu erat mattis porta. Pellentesque pharetra sed nunc eu egestas. Nam ut tellus consequat, feugiat ante sed, maximus arcu. Donec eget ipsum nibh.

Proin pellentesque urna ut leo malesuada, sed pharetra urna luctus. Curabitur tincidunt lorem id facilisis condimentum. Fusce vitae est accumsan, vehicula ante et, maximus lacus. Fusce sodales luctus hendrerit. Etiam et facilisis neque. Praesent fringilla, eros vitae fermentum feugiat, turpis nulla mattis neque, ac vulputate velit elit ac tellus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Mauris in neque porttitor, vestibulum tellus sit amet, consectetur velit. Integer at purus congue, molestie nisi vel, cursus purus. Donec tempus congue magna a condimentum. Maecenas a tristique mauris. Pellentesque dolor dolor, iaculis sed venenatis eu, volutpat eget nisl.

Ut vitae dolor egestas, scelerisque enim eu, maximus erat. Praesent in facilisis nisl. Cras pellentesque eros quis felis consectetur pharetra. Mauris mattis augue turpis, ut molestie leo tempor sit amet. Curabitur pretium metus mattis purus laoreet lacinia. Phasellus egestas commodo orci in sollicitudin. Nulla sagittis nulla ligula, et ornare felis hendrerit sit amet.

Donec metus tortor, viverra at erat porttitor, venenatis pulvinar ipsum. Mauris vestibulum orci sit amet felis tristique, sit amet varius nibh venenatis. Nulla ultricies erat non molestie finibus. Duis volutpat ut risus a sollicitudin. Praesent a neque neque. Suspendisse potenti. Maecenas maximus vel nulla non eleifend. Integer vel turpis ante. Praesent lobortis leo vel sapien porttitor, at fringilla nunc faucibus. Maecenas ut leo id quam tempus bibendum eu at ligula. Duis eu nunc non ipsum efficitur cursus et nec sapien. Nullam tempus in purus quis pharetra. ', TRUE, '04-04-2021', now()),
 
		(4,2,1,'Ocuba, the new boss rusher metroidvania', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer congue velit vitae tortor mattis, eget aliquam felis fermentum. Nunc magna orci, posuere quis convallis ut, ornare ac ligula. Curabitur ultrices rutrum nulla nec accumsan. Aliquam sit amet lacus semper, laoreet odio sit amet, volutpat odio. Mauris sagittis, eros non gravida commodo, libero nibh faucibus erat, at tincidunt ipsum lorem a dui. Nam neque nisl, faucibus sed sapien quis, efficitur sodales augue. Donec volutpat elit ac odio gravida porta.

Vivamus vulputate faucibus erat, ac viverra metus pretium et. Nulla lorem est, lobortis sed viverra sed, pulvinar et diam. Praesent eget neque a tortor tempus fringilla. Fusce rutrum magna a neque consequat sagittis. Nulla facilisi. Vivamus scelerisque justo at luctus maximus. Ut congue porttitor libero a vulputate. Morbi at dictum sapien. Nullam auctor ipsum sed volutpat iaculis. Vivamus sed enim quis velit ullamcorper tempor sit amet eu tellus. Vestibulum placerat a augue id accumsan. Curabitur at enim eu erat mattis porta. Pellentesque pharetra sed nunc eu egestas. Nam ut tellus consequat, feugiat ante sed, maximus arcu. Donec eget ipsum nibh.

Proin pellentesque urna ut leo malesuada, sed pharetra urna luctus. Curabitur tincidunt lorem id facilisis condimentum. Fusce vitae est accumsan, vehicula ante et, maximus lacus. Fusce sodales luctus hendrerit. Etiam et facilisis neque. Praesent fringilla, eros vitae fermentum feugiat, turpis nulla mattis neque, ac vulputate velit elit ac tellus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Mauris in neque porttitor, vestibulum tellus sit amet, consectetur velit. Integer at purus congue, molestie nisi vel, cursus purus. Donec tempus congue magna a condimentum. Maecenas a tristique mauris. Pellentesque dolor dolor, iaculis sed venenatis eu, volutpat eget nisl.

Ut vitae dolor egestas, scelerisque enim eu, maximus erat. Praesent in facilisis nisl. Cras pellentesque eros quis felis consectetur pharetra. Mauris mattis augue turpis, ut molestie leo tempor sit amet. Curabitur pretium metus mattis purus laoreet lacinia. Phasellus egestas commodo orci in sollicitudin. Nulla sagittis nulla ligula, et ornare felis hendrerit sit amet.

Donec metus tortor, viverra at erat porttitor, venenatis pulvinar ipsum. Mauris vestibulum orci sit amet felis tristique, sit amet varius nibh venenatis. Nulla ultricies erat non molestie finibus.', TRUE, '08-08-2021', now()),
		(5,2,1,'Ocuba Cancelled', 'Well, at least it has two playable bosses. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer congue velit vitae tortor mattis, eget aliquam felis fermentum. Nunc magna orci, posuere quis convallis ut, ornare ac ligula. Curabitur ultrices rutrum nulla nec accumsan. Aliquam sit amet lacus semper, laoreet odio sit amet, volutpat odio. Mauris sagittis, eros non gravida commodo, libero nibh faucibus erat, at tincidunt ipsum lorem a dui. Nam neque nisl, faucibus sed sapien quis, efficitur sodales augue. Donec volutpat elit ac odio gravida porta.

Vivamus vulputate faucibus erat, ac viverra metus pretium et. Nulla lorem est, lobortis sed viverra sed, pulvinar et diam. Praesent eget neque a tortor tempus fringilla. Fusce rutrum magna a neque consequat sagittis. Nulla facilisi. Vivamus scelerisque justo at luctus maximus. Ut congue porttitor libero a vulputate. Morbi at dictum sapien. Nullam auctor ipsum sed volutpat iaculis. Vivamus sed enim quis velit ullamcorper tempor sit amet eu tellus. Vestibulum placerat a augue id accumsan. Curabitur at enim eu erat mattis porta. Pellentesque pharetra sed nunc eu egestas. Nam ut tellus consequat, feugiat ante sed, maximus arcu. Donec eget ipsum nibh.

Proin pellentesque urna ut leo malesuada, sed pharetra urna luctus. Curabitur tincidunt lorem id facilisis condimentum. Fusce vitae est accumsan, vehicula ante et, maximus lacus. Fusce sodales luctus hendrerit. Etiam et facilisis neque. Praesent fringilla, eros vitae fermentum feugiat, turpis nulla mattis neque, ac vulputate velit elit ac tellus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Mauris in neque porttitor, vestibulum tellus sit amet, consectetur velit. Integer at purus congue, molestie nisi vel, cursus purus. Donec tempus congue magna a condimentum. Maecenas a tristique mauris. Pellentesque dolor dolor, iaculis sed venenatis eu, volutpat eget nisl.

Ut vitae dolor egestas, scelerisque enim eu, maximus erat. Praesent in facilisis nisl. Cras pellentesque eros quis felis consectetur pharetra. Mauris mattis augue turpis, ut molestie leo tempor sit amet. Curabitur pretium metus mattis purus laoreet lacinia. Phasellus egestas commodo orci in sollicitudin. Nulla sagittis nulla ligula, et ornare felis hendrerit sit amet.

Donec metus tortor, viverra at erat porttitor, venenatis pulvinar ipsum. Mauris vestibulum orci sit amet felis tristique, sit amet varius nibh venenatis. Nulla ultricies erat non molestie finibus.', TRUE, '11-11-2021', now()),
		(6,3,1, 'Google Chrome Dinosaur Game Copy', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer congue velit vitae tortor mattis, eget aliquam felis fermentum. Nunc magna orci, posuere quis convallis ut, ornare ac ligula. Curabitur ultrices rutrum nulla nec accumsan. Aliquam sit amet lacus semper, laoreet odio sit amet, volutpat odio. Mauris sagittis, eros non gravida commodo, libero nibh faucibus erat, at tincidunt ipsum lorem a dui. Nam neque nisl, faucibus sed sapien quis, efficitur sodales augue. Donec volutpat elit ac odio gravida porta.

Vivamus vulputate faucibus erat, ac viverra metus pretium et. Nulla lorem est, lobortis sed viverra sed, pulvinar et diam. Praesent eget neque a tortor tempus fringilla. Fusce rutrum magna a neque consequat sagittis. Nulla facilisi. Vivamus scelerisque justo at luctus maximus. Ut congue porttitor libero a vulputate. Morbi at dictum sapien. Nullam auctor ipsum sed volutpat iaculis. Vivamus sed enim quis velit ullamcorper tempor sit amet eu tellus. Vestibulum placerat a augue id accumsan. Curabitur at enim eu erat mattis porta. Pellentesque pharetra sed nunc eu egestas. Nam ut tellus consequat, feugiat ante sed, maximus arcu. Donec eget ipsum nibh.

Proin pellentesque urna ut leo malesuada, sed pharetra urna luctus. Curabitur tincidunt lorem id facilisis condimentum. Fusce vitae est accumsan, vehicula ante et, maximus lacus. Fusce sodales luctus hendrerit. Etiam et facilisis neque. Praesent fringilla, eros vitae fermentum feugiat, turpis nulla mattis neque, ac vulputate velit elit ac tellus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Mauris in neque porttitor, vestibulum tellus sit amet, consectetur velit. Integer at purus congue, molestie nisi vel, cursus purus. Donec tempus congue magna a condimentum. Maecenas a tristique mauris. Pellentesque dolor dolor, iaculis sed venenatis eu, volutpat eget nisl.

Ut vitae dolor egestas, scelerisque enim eu, maximus erat. Praesent in facilisis nisl. Cras pellentesque eros quis felis consectetur pharetra. Mauris mattis augue turpis, ut molestie leo tempor sit amet. Curabitur pretium metus mattis purus laoreet lacinia. Phasellus egestas commodo orci in sollicitudin. Nulla sagittis nulla ligula, et ornare felis hendrerit sit amet.

Donec metus tortor, viverra at erat porttitor, venenatis pulvinar ipsum. Mauris vestibulum orci sit amet felis tristique, sit amet varius nibh venenatis. Nulla ultricies erat non molestie finibus.', TRUE, '10-10-2020', now()),
		(7,3,1, 'Pagnea, now with aeroplanes and facists', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer congue velit vitae tortor mattis, eget aliquam felis fermentum. Nunc magna orci, posuere quis convallis ut, ornare ac ligula. Curabitur ultrices rutrum nulla nec accumsan. Aliquam sit amet lacus semper, laoreet odio sit amet, volutpat odio. Mauris sagittis, eros non gravida commodo, libero nibh faucibus erat, at tincidunt ipsum lorem a dui. Nam neque nisl, faucibus sed sapien quis, efficitur sodales augue. Donec volutpat elit ac odio gravida porta.

Vivamus vulputate faucibus erat, ac viverra metus pretium et. Nulla lorem est, lobortis sed viverra sed, pulvinar et diam. Praesent eget neque a tortor tempus fringilla. Fusce rutrum magna a neque consequat sagittis. Nulla facilisi. Vivamus scelerisque justo at luctus maximus. Ut congue porttitor libero a vulputate. Morbi at dictum sapien. Nullam auctor ipsum sed volutpat iaculis. Vivamus sed enim quis velit ullamcorper tempor sit amet eu tellus. Vestibulum placerat a augue id accumsan. Curabitur at enim eu erat mattis porta. Pellentesque pharetra sed nunc eu egestas. Nam ut tellus consequat, feugiat ante sed, maximus arcu. Donec eget ipsum nibh.

Proin pellentesque urna ut leo malesuada, sed pharetra urna luctus. Curabitur tincidunt lorem id facilisis condimentum. Fusce vitae est accumsan, vehicula ante et, maximus lacus. Fusce sodales luctus hendrerit. Etiam et facilisis neque. Praesent fringilla, eros vitae fermentum feugiat, turpis nulla mattis neque, ac vulputate velit elit ac tellus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Mauris in neque porttitor, vestibulum tellus sit amet, consectetur velit. Integer at purus congue, molestie nisi vel, cursus purus. Donec tempus congue magna a condimentum. Maecenas a tristique mauris. Pellentesque dolor dolor, iaculis sed venenatis eu, volutpat eget nisl.

Ut vitae dolor egestas, scelerisque enim eu, maximus erat. Praesent in facilisis nisl. Cras pellentesque eros quis felis consectetur pharetra. Mauris mattis augue turpis, ut molestie leo tempor sit amet. Curabitur pretium metus mattis purus laoreet lacinia. Phasellus egestas commodo orci in sollicitudin. Nulla sagittis nulla ligula, et ornare felis hendrerit sit amet.

Donec metus tortor, viverra at erat porttitor, venenatis pulvinar ipsum. Mauris vestibulum orci sit amet felis tristique, sit amet varius nibh venenatis. Nulla ultricies erat non molestie finibus.', TRUE, '11-11-2020', now()),
		(8,3,1, 'Dino Saurio Launch - V 1.0.0', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer congue velit vitae tortor mattis, eget aliquam felis fermentum. Nunc magna orci, posuere quis convallis ut, ornare ac ligula. Curabitur ultrices rutrum nulla nec accumsan. Aliquam sit amet lacus semper, laoreet odio sit amet, volutpat odio. Mauris sagittis, eros non gravida commodo, libero nibh faucibus erat, at tincidunt ipsum lorem a dui. Nam neque nisl, faucibus sed sapien quis, efficitur sodales augue. Donec volutpat elit ac odio gravida porta.

Vivamus vulputate faucibus erat, ac viverra metus pretium et. Nulla lorem est, lobortis sed viverra sed, pulvinar et diam. Praesent eget neque a tortor tempus fringilla. Fusce rutrum magna a neque consequat sagittis. Nulla facilisi. Vivamus scelerisque justo at luctus maximus. Ut congue porttitor libero a vulputate. Morbi at dictum sapien. Nullam auctor ipsum sed volutpat iaculis. Vivamus sed enim quis velit ullamcorper tempor sit amet eu tellus. Vestibulum placerat a augue id accumsan. Curabitur at enim eu erat mattis porta. Pellentesque pharetra sed nunc eu egestas. Nam ut tellus consequat, feugiat ante sed, maximus arcu. Donec eget ipsum nibh.

Proin pellentesque urna ut leo malesuada, sed pharetra urna luctus. Curabitur tincidunt lorem id facilisis condimentum. Fusce vitae est accumsan, vehicula ante et, maximus lacus. Fusce sodales luctus hendrerit. Etiam et facilisis neque. Praesent fringilla, eros vitae fermentum feugiat, turpis nulla mattis neque, ac vulputate velit elit ac tellus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Mauris in neque porttitor, vestibulum tellus sit amet, consectetur velit. Integer at purus congue, molestie nisi vel, cursus purus. Donec tempus congue magna a condimentum. Maecenas a tristique mauris. Pellentesque dolor dolor, iaculis sed venenatis eu, volutpat eget nisl.

Ut vitae dolor egestas, scelerisque enim eu, maximus erat. Praesent in facilisis nisl. Cras pellentesque eros quis felis consectetur pharetra. Mauris mattis augue turpis, ut molestie leo tempor sit amet. Curabitur pretium metus mattis purus laoreet lacinia. Phasellus egestas commodo orci in sollicitudin. Nulla sagittis nulla ligula, et ornare felis hendrerit sit amet.

Donec metus tortor, viverra at erat porttitor, venenatis pulvinar ipsum. Mauris vestibulum orci sit amet felis tristique, sit amet varius nibh venenatis. Nulla ultricies erat non molestie finibus.', TRUE, '12-12-2020', now());